# Generated by Django 3.0.5 on 2020-04-21 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200421_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='expiryDate',
            field=models.TimeField(default=datetime.datetime(2020, 4, 21, 13, 30, 31, 587109, tzinfo=utc)),
        ),
    ]
