# Generated by Django 3.0.5 on 2020-04-21 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200421_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expiryDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 13, 37, 58, 6700, tzinfo=utc)),
        ),
    ]
